name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:45 AM on Friday (somewhat randomly chosen).
    - cron: '45 5 * * 5'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform: [x86, x64]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-2019, windows-2022, windows-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }} / ${{ matrix.platform }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v1
        if: runner.os == 'Windows'
      - name: Set up Clang
        uses: ./
        with:
          platform: '${{ matrix.platform }}'
          cc: 1
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc

  versions:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: ['3.9', '4.0', 4, '5.0', 5, '6.0', 6, 7, 8, 9, 10, 11, 12, 13]
        exclude:
          - {os: ubuntu-20.04, version: '3.9'}
          - {os: ubuntu-20.04, version: '4.0'}
          - {os: ubuntu-20.04, version: 4}
          - {os: ubuntu-20.04, version: '5.0'}
          - {os: ubuntu-20.04, version: 5}
    runs-on: '${{ matrix.os }}'
    name: 'Version: ${{ matrix.os }} / ${{ matrix.version }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: setup
        name: Set up Clang
        uses: ./
        with:
          version: '${{ matrix.version }}'
          platform: '${{ matrix.platform }}'
          cc: 1
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
        with:
          binary: '${{ steps.setup.outputs.clangxx }}'
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc
        with:
          version: '${{ matrix.version }}'

  cygwin:
    strategy:
      matrix:
        hardlinks: [0, 1]
    runs-on: windows-latest
    name: 'Cygwin: hardlinks${{ matrix.hardlinks }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v1
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
      - name: Set up Clang
        uses: ./
        with:
          cygwin: 1
          cc: 1
          hardlinks: '${{ matrix.hardlinks }}'
      - name: Build foo.exe
        uses: ./.github/actions/build-foo
        if: matrix.hardlinks
      - name: Build foo.exe
        uses: ./.github/actions/build-foo-cygwin
        if: '!matrix.hardlinks'
      - name: Run foo.exe
        uses: ./.github/actions/run-foo
      - name: Check symlinks
        uses: ./.github/actions/check-cc
        if: matrix.hardlinks
      - name: Check symlinks
        uses: ./.github/actions/check-cc-cygwin
        if: '!matrix.hardlinks'
